services:
  api-students:
    build: ./api-students
    container_name: api_students
    ports:
      - "9000:9000"
    
    environment:
      DB_HOST: mysql_db  # Nom du conteneur de la base de données
      DB_USER: api_user  # Utilisateur API
      DB_PASSWORD: api_2025  #Mot de passe API
      DB_NAME: students_db  # Nom de la base de données
      DB_PORT: 3306  # Port de la base de données
    networks:
      - my_network  
    depends_on:
      - api-students-db
    restart: always

  api-students-db:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root2025  
      MYSQL_DATABASE: students_db
      MYSQL_USER: api_user 
      MYSQL_PASSWORD: api_2025
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network
  
  api-absences:
    build: ./api-absences
    container_name: api_absences
    ports:
      - "7000:7000"

    environment:
      MONGO_DB_NAME : "absences_db"
      MONGO_DB_USER : "mongo_user"
      MONGO_DB_PASSWORD : "mongo_pass"
      MONGO_DB_HOST : "mongo_db"
      MONGO_DB_PORT : 27017
    networks:
      - my_network
  
  mongo_db:
    image: mongo
    container_name: "mongo_db"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
      MONGO_INITDB_DATABASE: absences_db
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network
    
volumes:
  mysql_data:
  mongo_data:
  
networks:
  my_network: