# Utilisez une image Node.js en tant qu'image de base
ARG NODE_VERSION=22.13.0

FROM node:${NODE_VERSION}-alpine
# Définir le répertoire de travail dans le conteneur
WORKDIR /usr/src/app
# Copier le package.json et le package-lock.json dans le conteneur
COPY package*.json ./
# Installer les dépendances du projet
RUN npm install
# Copier le reste des fichiers de l'application dans le conteneur
COPY . .

# Commande pour exécuter l'application lorsque le conteneur démarre
CMD [ "node", "server.js" ]